from datetime import datetime
from typing import Generic, Optional, Protocol, TypeVar

Entity = TypeVar('Entity')


class AbstractRepositoryInterface(Protocol, Generic[Entity]):
    def create(self, entity: Entity) -> Entity: ...

    def update(self, entity: Entity) -> Entity: ...

    def delete(self, entity_id: str) -> None: ...

    def get_by_id(self, entity_id: str) -> Optional[Entity]: ...

    def get_by_created_at(self, created_at: datetime) -> list[Entity]: ...

    def get_by_updated_at(self, updated_at: datetime) -> list[Entity]: ...