from datetime import datetime
from typing import Protocol

from application.ports.default_repo import AbstractRepository
from src.domain.entities.loan import BookLoan


class BookLoanRepository(AbstractRepository[BookLoan], Protocol):
    def get_by_id_book(self, id_book: str) -> list[BookLoan]: ...

    def get_by_id_student(self, id_student: str) -> list[BookLoan]: ...

    def get_by_checked_in(self, checked_in: datetime) -> list[BookLoan]: ...

    def get_by_checked_out(self, checked_out: datetime) -> list[BookLoan]: ...

    def get_checked_today(self) -> list[BookLoan]: ...

    def set_book_return(self, entity_id: str) -> None: ...