
from contextlib import AbstractContextManager

from typing import Any, Optional, Protocol


class DBInterface(Protocol):
        
    def _config(self) -> None: ...

    def connect(self) -> None: ...

    def transaction(self) -> AbstractContextManager[None]: ...

    def execute(self, query: str, params: tuple[Optional[Any], ...] = ()) -> None: ...

    def fetchone(self, query: str, params: tuple[Optional[Any], ...] = ()) -> Optional[Any]: ...

    def fetchall(self, query: str, params: tuple[Optional[Any], ...] = ()) -> list[Any]: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def close(self) -> None: ...